# Generated by Django 4.1 on 2022-08-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=108)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
